# Part 1

# on: [push]
# jobs:
#   display_files:
#     name: run a sample command
#     runs-on: ubuntu-latest
#     steps:        
#       - name: display output
#         run: |
#           echo "Hello World"
#         shell: bash

# Part 2

# on:
#   push:
#     branches:
#     - master
# permissions:
#   pull-requests: write
#   contents: write
#   repository-projects: write
# jobs:
#   display_files:
#     name: job name display file content
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout repository
#         uses: actions/checkout@v2
#       - name: display file content
        # run: |
        #   cat test.txt
        # shell: bash


# Part 3

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Job 1 is executed successfully"

  job2:
    runs-on: ubuntu-latest
    needs: job1 #for dependent jobs
    steps:
      - name: Job 2
        run: echo "Job 2 executed successfully"
