# on: [push]
# jobs:
#   display_files:
#     name: run a sample command
#     runs-on: ubuntu-latest
#     steps:        
#       - name: display output
#         run: |
#           echo "Hello World"
#         shell: bash


on:
  push:
    branches:
    - master
permissions:
  pull-requests: write
  contents: write
  repository-projects: write
jobs:
  display_files:
    name: job name display file content
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: display file content
        run: |
          cat test.txt
        shell: bash
